
version: '3.9'
services:
  db:
    image: mysql:8.0.27
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: paro1_mysq1
      MYSQL_DATABASE: carts
      MYSQL_USER: mysql
      MYSQL_PASSWORD: musql_0z
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql


  cartrige:
    container_name: cartrige
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./cartrige:/usr/src/app/cartrige
volumes:
  dbdata:
