# Generated by Django 3.2.2 on 2021-12-02 23:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartriges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cart', models.CharField(max_length=25, unique=True, verbose_name='Картридж')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото')),
                ('comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name_plural': 'Картриджи',
                'ordering': ['name_cart'],
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_depart', models.CharField(help_text='Введите наименование подразделения', max_length=100, unique=True, verbose_name='Наименование подразделения')),
                ('fio', models.CharField(blank=True, help_text='Введите ФИО ответственного от подразделения', max_length=40, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name_depart'],
            },
        ),
        migrations.CreateModel(
            name='Nmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapis', models.IntegerField(default=0)),
                ('nmax', models.IntegerField(verbose_name='Текущий максимальный номер картриджа')),
            ],
            options={
                'verbose_name_plural': 'Максимальный номер',
            },
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_buh', models.CharField(help_text='Введите модель картриджа по бухгалтерии', max_length=30, unique=True, verbose_name='Картридж по бухгалтерии')),
                ('cart_count', models.IntegerField(default=0, verbose_name='Количество')),
                ('id_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.cartriges', verbose_name='Картридж')),
            ],
            options={
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_printer', models.CharField(help_text='Введите модель принтера', max_length=25, unique=True, verbose_name='Принтер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото')),
                ('printer_count', models.IntegerField(default=0, verbose_name='Количество')),
                ('cart', models.ManyToManyField(related_name='carts', to='cartrige.Cartriges')),
            ],
            options={
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Oborot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar', models.IntegerField(null=True, unique=True, verbose_name='Инв.N')),
                ('charge_num', models.IntegerField(default=1, verbose_name='Количество заправок')),
                ('status', models.CharField(choices=[('1', 'Новый'), ('2', 'Установлен'), ('3', 'Пустой'), ('4', 'Заправка'), ('5', 'Заправлен'), ('6', 'Дефект'), ('7', 'Списан')], default='5', help_text='Статус картриджа', max_length=1, verbose_name='Статус')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата передачи')),
                ('comment', models.TextField(blank=True, help_text='Комментарий', max_length=300, null=True, verbose_name='Примечание')),
                ('id_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.cartriges', verbose_name='Картридж')),
                ('id_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.depart', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name_plural': 'В работе',
                'ordering': ['inventar'],
            },
        ),
    ]
