# Generated by Django 3.2.2 on 2022-05-07 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartriges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cart', models.CharField(max_length=50, unique=True, verbose_name='Картридж')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото')),
                ('comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name_plural': 'Модели картриджей',
                'ordering': ['name_cart'],
            },
        ),
        migrations.CreateModel(
            name='ContrAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_agent', models.CharField(max_length=50, unique=True, verbose_name='Краткое наименование')),
                ('name_agent_full', models.CharField(max_length=150, verbose_name='Полное наименование')),
                ('fio_nach', models.CharField(blank=True, max_length=40, verbose_name='Руководитель')),
                ('nach_dolj', models.CharField(blank=True, max_length=40, verbose_name='Должность руководителя')),
                ('fio_zam', models.CharField(blank=True, max_length=40, verbose_name='Зам.руководителя')),
                ('inn', models.CharField(blank=True, max_length=100, verbose_name='ИНН, КПП, ОГРН и т.д.')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Е-майл')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('otvet', models.CharField(blank=True, max_length=25, verbose_name='Приемщик')),
                ('adm', models.BooleanField(default=False, verbose_name='Наша организация')),
            ],
            options={
                'verbose_name_plural': 'Контрагент',
                'ordering': ['name_agent'],
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_depart', models.CharField(max_length=100, unique=True, verbose_name='Наименование подразделения')),
                ('fio', models.CharField(blank=True, max_length=40, verbose_name='Начальник/Ответственный')),
                ('adm', models.BooleanField(default=False, verbose_name='Отдел IT')),
            ],
            options={
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name_depart'],
            },
        ),
        migrations.CreateModel(
            name='MetaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.CharField(max_length=40, unique=True, verbose_name='Наименование группы')),
            ],
            options={
                'verbose_name_plural': 'Группы картриджей',
                'ordering': ['metatitle'],
            },
        ),
        migrations.CreateModel(
            name='Nmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapis', models.IntegerField(default=0)),
                ('nmax', models.IntegerField(verbose_name='Текущий максимальный номер картриджа')),
            ],
            options={
                'verbose_name_plural': 'Максимальный номер',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(verbose_name='Код операции')),
                ('operation_name', models.CharField(max_length=25, verbose_name='Операция')),
            ],
            options={
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(default=2022)),
                ('meta', models.CharField(blank=True, max_length=50, null=True)),
                ('oper', models.CharField(blank=True, max_length=50, null=True)),
                ('actid', models.IntegerField(default=0)),
                ('m1', models.IntegerField(default=0)),
                ('m2', models.IntegerField(default=0)),
                ('m3', models.IntegerField(default=0)),
                ('m4', models.IntegerField(default=0)),
                ('m5', models.IntegerField(default=0)),
                ('m6', models.IntegerField(default=0)),
                ('m7', models.IntegerField(default=0)),
                ('m8', models.IntegerField(default=0)),
                ('m9', models.IntegerField(default=0)),
                ('m10', models.IntegerField(default=0)),
                ('m11', models.IntegerField(default=0)),
                ('m12', models.IntegerField(default=0)),
                ('msum', models.IntegerField(default=0)),
                ('ord', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_buh', models.CharField(max_length=255, unique=True, verbose_name='Картридж по бухгалтерии')),
                ('cart_count', models.IntegerField(default=0, verbose_name='Количество')),
                ('cartriges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.cartriges', verbose_name='Картридж')),
            ],
            options={
                'verbose_name_plural': 'Склад',
                'ordering': ['cartriges'],
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_created=True, auto_now=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('inventar', models.IntegerField(null=True, unique=True, verbose_name='Учетный N')),
                ('charge_num', models.IntegerField(default=1, verbose_name='Количество заправок')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новый'), (2, 'Установлен'), (3, 'Пустой'), (4, 'Заправка'), (5, 'Заправлен'), (6, 'Дефект'), (7, 'Списан')], default=5, help_text='Статус картриджа', verbose_name='Статус')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата передачи/списания')),
                ('comment', models.TextField(blank=True, help_text='Комментарий', max_length=300, null=True, verbose_name='Комментарий')),
                ('tkn', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Токен')),
                ('c_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.contragent', verbose_name='Контрагент')),
                ('id_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.cartriges', verbose_name='Картридж')),
                ('id_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.depart', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name_plural': 'Учет',
                'ordering': ['inventar'],
            },
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_printer', models.CharField(max_length=100, unique=True, verbose_name='Принтер')),
                ('photo_prn', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото')),
                ('cart', models.ManyToManyField(blank=True, related_name='carts', to='cartrige.Cartriges', verbose_name='Совместимые картриджи')),
            ],
            options={
                'verbose_name_plural': 'Модели принтеров',
                'ordering': ['name_printer'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время события')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Токен')),
                ('name_user', models.CharField(max_length=15, verbose_name='Пользователь')),
                ('izm', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подробно')),
                ('dep', models.IntegerField(null=True, verbose_name='ID подразделения')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.operation', verbose_name='Операция')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.records', verbose_name='ID_объекта')),
            ],
            options={
                'verbose_name_plural': 'Логи',
                'ordering': ['-date_event'],
            },
        ),
        migrations.AddField(
            model_name='cartriges',
            name='metacart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.metacart', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='AllPrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar_num', models.CharField(max_length=10, unique=True, verbose_name='Серийный номер')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.depart', verbose_name='Подразделение')),
                ('printer_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.printers', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name_plural': 'Принтеры организации',
                'ordering': ['printer_model'],
            },
        ),
    ]
