# Generated by Django 3.2.2 on 2021-12-03 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printers',
            options={'ordering': ['name_printer'], 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterField(
            model_name='printers',
            name='cart',
            field=models.ManyToManyField(related_name='carts', to='cartrige.Cartriges', verbose_name='Совместимые картриджи'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/printers/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото'),
        ),
    ]
