# Generated by Django 3.2.2 on 2022-03-10 23:45

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Nmax = apps.get_model("cartrige", "Nmax")
    db_alias = schema_editor.connection.alias
    Nmax.objects.using(db_alias).bulk_create([
        Nmax(zapis=0, nmax=100),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
