# Generated by Django 3.2.2 on 2021-12-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0002_auto_20211203_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printers',
            old_name='photo',
            new_name='photo_prn',
        ),
    ]
