# Generated by Django 3.2.2 on 2022-03-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0002_auto_20220311_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='dep',
            field=models.IntegerField(null=True, verbose_name='ID подразделения'),
        ),
    ]
