# Generated by Django 3.2.2 on 2021-12-09 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0003_rename_photo_printers_photo_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='photo_prn',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator], verbose_name='Фото'),
        ),
    ]
