# Generated by Django 3.2.2 on 2021-12-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0005_auto_20211210_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printers',
            name='printer_count',
        ),
    ]
