# Generated by Django 3.2.2 on 2021-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0006_remove_printers_printer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depart',
            name='fio',
            field=models.CharField(blank=True, max_length=40, verbose_name='Начальник/Ответственный'),
        ),
        migrations.AlterField(
            model_name='depart',
            name='name_depart',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование подразделения'),
        ),
    ]
