# Generated by Django 3.2.2 on 2021-12-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0007_auto_20211211_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printers',
            options={'ordering': ['name_printer'], 'verbose_name_plural': 'Модели принтеров'},
        ),
        migrations.CreateModel(
            name='AllPrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar_num', models.IntegerField(unique=True, verbose_name='Инвентарный номер')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.depart', verbose_name='Подразделение')),
                ('printer_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.printers', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name_plural': 'Принтеры организации',
                'ordering': ['printer_model'],
            },
        ),
    ]
