# Generated by Django 3.2.2 on 2021-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0009_auto_20211211_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprinters',
            name='inventar_num',
            field=models.CharField(max_length=10, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
