# Generated by Django 3.2.2 on 2021-12-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0010_alter_allprinters_inventar_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartriges',
            options={'ordering': ['name_cart'], 'verbose_name_plural': 'Модели картриджей'},
        ),
        migrations.AlterField(
            model_name='allprinters',
            name='inventar_num',
            field=models.CharField(max_length=10, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.CreateModel(
            name='MetaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.CharField(max_length=20, verbose_name='Наименование группы')),
                ('cart_from_meta', models.ManyToManyField(blank=True, related_name='cards', to='cartrige.Cartriges', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Метагруппы картриджей',
                'ordering': ['metatitle'],
            },
        ),
    ]
