# Generated by Django 3.2.2 on 2021-12-15 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0011_auto_20211215_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacart',
            name='cart_from_meta',
        ),
        migrations.AddField(
            model_name='cartriges',
            name='meta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cartrige.metacart', verbose_name='Метагруппа'),
        ),
        migrations.AlterField(
            model_name='metacart',
            name='metatitle',
            field=models.CharField(max_length=20, unique=True, verbose_name='Наименование группы'),
        ),
    ]
