# Generated by Django 3.2.2 on 2021-12-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0012_auto_20211215_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartriges',
            name='meta',
        ),
        migrations.AddField(
            model_name='metacart',
            name='cart_from_meta',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cartrige.Cartriges', verbose_name='Группа'),
        ),
    ]
