# Generated by Django 3.2.2 on 2021-12-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0013_auto_20211215_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacart',
            name='cart_from_meta',
        ),
        migrations.AddField(
            model_name='cartriges',
            name='metacart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metacart', to='cartrige.metacart', verbose_name='Группа'),
        ),
    ]
