# Generated by Django 3.2.2 on 2021-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0014_auto_20211215_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metacart',
            options={'ordering': ['metatitle'], 'verbose_name_plural': 'Группы картриджей'},
        ),
        migrations.RemoveField(
            model_name='cartriges',
            name='metacart',
        ),
        migrations.AddField(
            model_name='metacart',
            name='metacart',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cartrige.Cartriges', verbose_name='Группа'),
        ),
    ]
