# Generated by Django 3.2.2 on 2021-12-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0017_auto_20211215_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartriges',
            name='metacart',
        ),
        migrations.AddField(
            model_name='cartriges',
            name='metacart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metacart', to='cartrige.metacart', verbose_name='Группа'),
        ),
    ]
