# Generated by Django 3.2.2 on 2021-12-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0021_alter_cartriges_metacart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar', models.IntegerField(null=True, unique=True, verbose_name='Учетный N')),
                ('charge_num', models.IntegerField(default=1, verbose_name='Количество заправок')),
                ('status', models.CharField(choices=[('1', 'Новый'), ('2', 'Установлен'), ('3', 'Пустой'), ('4', 'Заправка'), ('5', 'Заправлен'), ('6', 'Дефект'), ('7', 'Списан')], default='5', help_text='Статус картриджа', max_length=1, verbose_name='Статус')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата передачи')),
                ('comment', models.TextField(blank=True, help_text='Комментарий', max_length=300, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name_plural': 'Учет',
                'ordering': ['inventar'],
            },
        ),
        migrations.AlterModelOptions(
            name='cartriges',
            options={'ordering': ['metacart', 'name_cart'], 'verbose_name_plural': 'Модели картриджей'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'ordering': ['id_cart'], 'verbose_name_plural': 'Склад'},
        ),
        migrations.DeleteModel(
            name='Oborot',
        ),
        migrations.AddField(
            model_name='records',
            name='id_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.cartriges', verbose_name='Картридж'),
        ),
        migrations.AddField(
            model_name='records',
            name='id_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.depart', verbose_name='Подразделение'),
        ),
    ]
