# Generated by Django 3.2.2 on 2021-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0022_auto_20211217_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'Установлен'), (3, 'Пустой'), (4, 'Заправка'), (5, 'Заправлен'), (6, 'Дефект'), (7, 'Списан')], default=5, help_text='Статус картриджа', max_length=1, verbose_name='Статус'),
        ),
    ]
