# Generated by Django 3.2.2 on 2021-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0026_auto_20211222_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='depart',
            name='adm',
            field=models.BooleanField(default=False, verbose_name='Отдел IT'),
        ),
    ]
