# Generated by Django 3.2.2 on 2022-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0027_depart_adm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_agent', models.CharField(max_length=50, unique=True, verbose_name='Краткое наименование заправщика')),
                ('name_agent_full', models.CharField(max_length=150, unique=True, verbose_name='Полное наименование заправщика')),
                ('fio_nach', models.CharField(blank=True, max_length=40, verbose_name='Начальник/Ответственный')),
                ('inn', models.CharField(blank=True, max_length=100, verbose_name='ИНН, КПП, ОГРН и т.д.')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Контрагент',
                'ordering': ['name_agent'],
            },
        ),
        migrations.AlterModelOptions(
            name='cartriges',
            options={'ordering': ['name_cart'], 'verbose_name_plural': 'Модели картриджей'},
        ),
    ]
