# Generated by Django 3.2.2 on 2022-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0028_auto_20220108_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='otvet',
            field=models.CharField(blank=True, max_length=25, verbose_name='Приемщик'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='fio_nach',
            field=models.CharField(blank=True, max_length=25, verbose_name='Начальник/Ответственный'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='name_agent_full',
            field=models.CharField(max_length=150, verbose_name='Полное наименование заправщика'),
        ),
    ]
