# Generated by Django 3.2.2 on 2022-01-11 10:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0029_auto_20220108_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='adm',
            field=models.BooleanField(default=False, verbose_name='Наша организация'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Е-майл'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='fio_zam',
            field=models.CharField(blank=True, max_length=40, verbose_name='Зам.руководителя'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='nach_dolj',
            field=models.CharField(blank=True, max_length=40, verbose_name='Должность руководителя'),
        ),
        migrations.AddField(
            model_name='contragent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='fio_nach',
            field=models.CharField(blank=True, max_length=40, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='name_agent',
            field=models.CharField(max_length=50, unique=True, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='name_agent_full',
            field=models.CharField(max_length=150, verbose_name='Полное наименование'),
        ),
    ]
