# Generated by Django 3.2.2 on 2022-01-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0030_auto_20220111_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время события')),
                ('name_user', models.CharField(max_length=15, verbose_name='Пользователь')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Создание'), (2, 'Редактирование'), (3, 'Удаление')], default=0, help_text='Действие', verbose_name='Действие')),
                ('name_table', models.CharField(max_length=25, verbose_name='Таблица')),
                ('obj', models.IntegerField(verbose_name='ID объекта')),
                ('izm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Что изменено')),
            ],
            options={
                'ordering': ['date_event'],
            },
        ),
    ]
