# Generated by Django 3.2.2 on 2022-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0031_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['date_event'], 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='date_event',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='Дата и время события'),
        ),
    ]
