# Generated by Django 3.2.2 on 2022-01-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0032_auto_20220114_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date_event',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время события'),
        ),
    ]
