# Generated by Django 3.2.2 on 2022-01-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0033_alter_logs_date_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='c_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartrige.contragent', verbose_name='Контрагент'),
        ),
    ]
