# Generated by Django 3.2.2 on 2022-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0036_alter_records_c_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-date_event'], 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='izm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подробно'),
        ),
    ]
