# Generated by Django 3.2.2 on 2022-01-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0037_auto_20220126_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='token',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
