# Generated by Django 3.2.2 on 2022-02-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0039_auto_20220131_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.CharField(blank=True, max_length=4, null=True)),
                ('meta', models.CharField(blank=True, max_length=40, null=True)),
                ('oper', models.CharField(blank=True, max_length=25, null=True)),
                ('actid', models.IntegerField(default=0)),
                ('m1', models.IntegerField(default=0)),
                ('m2', models.IntegerField(default=0)),
                ('m3', models.IntegerField(default=0)),
                ('m4', models.IntegerField(default=0)),
                ('m5', models.IntegerField(default=0)),
                ('m6', models.IntegerField(default=0)),
                ('m7', models.IntegerField(default=0)),
                ('m8', models.IntegerField(default=0)),
                ('m9', models.IntegerField(default=0)),
                ('m10', models.IntegerField(default=0)),
                ('m11', models.IntegerField(default=0)),
                ('m12', models.IntegerField(default=0)),
                ('msum', models.IntegerField(default=0)),
                ('ord', models.IntegerField(default=0)),
            ],
        ),
    ]
