# Generated by Django 3.2.2 on 2022-02-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0040_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp',
            name='god',
            field=models.IntegerField(default=2022),
        ),
    ]
