# Generated by Django 3.2.2 on 2022-02-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0041_alter_tmp_god'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartriges',
            name='metacart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cartrige.metacart', verbose_name='Группа'),
        ),
    ]
