# Generated by Django 3.2.2 on 2022-02-12 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartrige', '0043_alter_cartriges_metacart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='id_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.cartriges', verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='records',
            name='id_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.depart', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='cartriges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cartrige.cartriges', verbose_name='Картридж'),
        ),
    ]
